### ISSUE TITLE
Errors when zooming out too far

### ISSUE THREAD

**Issue by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#132]
Hi,

I can got two errors if I **strongly** zoom out on a graph:

1. with autorange: "Error fetching statistics of sensor www: invalid time value"
![2022-11-09 22_35_22-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/200946819-5dd9fbc7-2a61-4ad4-805f-fa5e7450fdfe.png)

2. without autorange (I set to `hour`): "Error computing range subtraction. Please report an issue in the repo of this card and share this:[null,78881237551759][-36938741245913,1668029462988]"
![2022-11-09 22_41_09-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/200947890-6bf6aaee-2b25-4806-9a9b-9ab8de3538a2.png)

**Comment by dbuezas** [comment]
I think we can validate that the API is returning sensible data. I'm not sure if the error message should still be shown so the user knows that HA is not happy with the range. WDYT?

**Comment by r-jean-pierre** [comment]
Throwing error and stopping the component is quite strong. I thought that at some point the date range is so huge that somewhere there is a division by 0 or something similar due to some snowball effect. Anyway, at that level of zoom, in the best case scenario only one pixel could remain visible on the graph, so 1 pixel vs a blank graph is somehow the same for the noob-end-user and nobody will even detect or think about it

PS: zoom in does not crash but the rendering is sometime illogical when close to the millisecond 

And by curiosity, do you know who is unhappy : HA, plotly, or the component itself?

**Comment by dbuezas** [comment]
> And by curiosity, do you know who is unhappy : HA, plotly, or the component itself?

I think HA is unhappy about the range and returns ill formatted data(or probably an error Im not handling)
When that happens, the cached-ranges bookkeeper starts doing math with undefineds and NaNs and everything goes down the drain from then on: plotlyjs is asked to plot empty series, which breaks the x axis. This triggers a re fetch on ridiculous dates, making HA even sadder. All results in the card getting depressed too. Luckily the reset button is very effective as therapy

**Comment by dbuezas** [comment]
I am looking at this issue.
I'm using unix timestamps (milliseconds since January 1, 1970), so when one zooms out a lot, these become negative. Obviously not something I took into account, but somewhat surprisingly, timestamps become negative and everything still works ok.
The real problems start when one zooms out into negative years: at that point, plotly reports the iso dates as "-0152-12-11 08:53:03.938" (this is the year -11), and the iso dates parser lib I'm using has no clue on how to handle that and returns NaN.

This is not something a normal user should face, but I do like when software feels solid, so I'll try to fix it without resetting the axes.

**Comment by dbuezas** [comment]
The HA API can't handle negative years. Which doesn't surprise me.
I'll cap the fetches to the year zero, but will let plotly go beyond there so one can do something with lambdas if one wants. I can't come up with a use case for this nonsense, but why not
