### ISSUE TITLE
Don't drop state duplicates when rendering the graph

### ISSUE THREAD

**Issue by zanna-37** [dbuezas/lovelace-plotly-graph-card#34]
**Edit:**
Since the code is dropping duplicate values, the graph is not able to handle sensors that rarely changes because it draws a straight line between the first two different values, which is not right.
I found that the cause should be to remove `minimal_response` here:
https://github.com/dbuezas/lovelace-plotly-graph-card/blob/de5c39ed72c93cb7973bcd696f7e5c55ebebd1ee/src/Cache.ts#L26

The reason is that:

> With minimal response we do not care about attribute changes so we can filter out duplicate states

https://github.com/home-assistant/core/blob/9864090e0b414b0c610cd0c33c6a49f81940bb9d/homeassistant/components/recorder/history.py#L417-L421

-----
<details>
  <summary>
    Old comment (you can ignore it)
  </summary>

**I keep this content for reference, but please do not consider it.**
With `significant_changes_only`, the graph is not able to handle sensors that rarely changes because it draws a straight line between the first two different values, which is not right.

Please consider changing `significant_changes_only=1` to `significant_changes_only=0` in https://github.com/dbuezas/lovelace-plotly-graph-card/blob/de5c39ed72c93cb7973bcd696f7e5c55ebebd1ee/src/Cache.ts#L25 or at least make it configurable.

Moreover, it seems that `significant_changes_only` alone is not enough, I saw that here
https://github.com/dbuezas/lovelace-plotly-graph-card/blob/de5c39ed72c93cb7973bcd696f7e5c55ebebd1ee/src/Cache.ts#L136-L142 you are trying to remove duplicate values, but there are cases in which those values are desirable.

And I suspect that there should be other places in the code that tries to remove the duplicates.
</details>

**Comment by dbuezas** [comment]
Hey zanna,
are you using a different trace shape?
https://plotly.com/javascript/reference/scatter/#scatter-line-shape

Using hv can be limiting of course, but it doesn't have the issue you describe.

And yes, I can make this configurable or just remove it at the cost of the plot getting slower (I didn't actually test this).

Out of curiosity, would you tell a bit more about what you are plotting?

**Comment by zanna-37** [comment]
I'm plotting energy consumption and solar production. To state an example, during the day the energy absorbed from the grid is 0, however, during the night, when the batteries are depleted, I switch to taking power from the grid. The power goes from 0 to the current energy consumption (e.g., from 0 to 700W).
With the current behavior, the plot draws a straight line between the first time it was 0 and the time it goes to 700W, which is clearly wrong.

I'm using `shape: spline` and averaging the values with a time window, and yes I found `hv` a bit limiting.

By the way, I was sure that `significant_changes_only` was meant to remove duplicates, but I solved the issue only by removing `minimal_response`. The documentation is not clear. Do you have more insights? Thank you for your time. =)

**Comment by zanna-37** [comment]
I found why `minimal_response` drops duplicates:

> With minimal response we do not care about attribute changes so we can filter out duplicate states

https://github.com/home-assistant/core/blob/9864090e0b414b0c610cd0c33c6a49f81940bb9d/homeassistant/components/recorder/history.py#L417-L421

**Comment by dbuezas** [comment]
Ohhh, that's why the sun angle plot doesn't work!

**Comment by dbuezas** [comment]
I think I'll remove the attribute as you say.
The only issue is that when the plot updates, HA responds repeating the last known value but with the a timestamp representing the present, so there are dups there

**Comment by dbuezas** [comment]
If you want to make a PR, you are welcome btw

**Comment by zanna-37** [comment]
> I think I'll remove the attribute as you say. The only issue is that when the plot updates, HA responds repeating the last known value but with the a timestamp representing the present, so there are dups there

Do you think it will be an issue?

**Comment by dbuezas** [comment]
Well, if the card is open for a long time, it would accumulate a lot of points. But it is a bit of an unusual case.

**Comment by zanna-37** [comment]
> If you want to make a PR, you are welcome btw

What do you have in mind? Removing the `minimal_response` is literally a 1 line edit. Using a yaml field to decide whether or not removing it is another story.

**Comment by dbuezas** [comment]
Ok, I'm taking a look and I have some news:
1. If I remove `minimal_response`, home assistant also sends all attribute values, which increases the payload by a big factor. I can add extra configurations to do that.
2. Removing `significant_changes_only=0` sounds reasonable enough to avoid your issue, I can do that by default.
3. The code you sent about `isRepeated` is _supposed_ to remove duplicates artificially created by home assistant. 

## The issue with isRepeated
Whenever you ask it for the data in a range, HA adds an extra datapoint at the beginning with the last known value (before the range you asked for).  I think this is why: [here](https://github.com/home-assistant/core/blob/9864090e0b414b0c610cd0c33c6a49f81940bb9d/homeassistant/components/recorder/history.py#L386)
Well, my solution only worked if the last plot update brought one single element, so that's a bug. 

The issue I have now, is that since I only ask for data on the not-yet-fecthed range intervals, I have no way to know which points are _fake_  and which aren't, so I can't just always remove the first datapoint assuming it is "fake".
This means that on each update, I end up adding a new point where there shouldn't be one. 

The only solution I see is to always fetch a range that starts on the last known datapoint. This way I can safely remove that one. 

Do you see any simpler solution?

**Comment by dbuezas** [comment]
I did something that seems to work, but it is a mess.
If you have any ideas let me know, I am willing to release what I did, but I won't understand it anymore in a week :/ 
![Kapture 2022-03-27 at 19 42 27](https://user-images.githubusercontent.com/777196/160293740-ad2101f2-347a-4fe5-ac79-93391a3a26b2.gif)
.

**Comment by dbuezas** [comment]
Every update (from update_interval) currently adds duplicated values at the front of the plot. I see that's not your main problem. I assumed it was one of the issues you have since you pointed out to that function.

**Comment by dbuezas** [comment]
Hey @zanna-37 could you try this beta release?
https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v1.3.0
I pushed the improved duplicate removal algorithm and added options to set both significant_changes_only and minimal_response.
Let me know if your issue is solved and I'll make it a final release.

**Comment by zanna-37** [comment]
Give me some days and I'll report back.
By the way, many thanks for your work!
