### ISSUE TITLE
More period options

### ISSUE THREAD

**Issue by smeingast** [dbuezas/lovelace-plotly-graph-card#448]
**Describe the solution you'd like**

Currently, there are six period options implemented: `5minute`, `hour`, `day`, `week`, `month`, `auto`. However, the steps between these are uneven and large so that for given displayed time periods there is no optimum. For instance, going from 5 minutes to 1 hour is a factor of 12, from hour to day is a factor of 24, then a factor of 7 from day to week, and a factor of about 4.5 from week to month. 

In order to have smaller steps, I propose to add more options, such as '10minute', '30minute', '2hour', '6hour', '12hour', '3day', '2week'.

**How would it be defined in yaml?**
By adding more options to the currently available ones.

**Comment by dbuezas** [comment]
These are not in my control, home assistant stores long term statistics in the db and its API offers only those granularities. That's why the native statistics card offers exactly the same period options too (https://www.home-assistant.io/dashboards/statistics-graph#period)

The only thing that could be done is to fetch the hourly period and then resample locally, which can be done with the resample filter

**Comment by smeingast** [comment]
No worries at all, and thank you for your quick response! I'll definitely look into the resampling option. Thanks again!
