### ISSUE TITLE
use more space for the card

### ISSUE THREAD

**Issue by Bascht74** [dbuezas/lovelace-plotly-graph-card#88]
as wished in https://github.com/dbuezas/lovelace-plotly-graph-card/issues/85 :

Could the width of the card be better used in the standard layout?
As you can see there is a bigger right boarder on the right side that could be used for the graph...
(Just compare to the "standard" history graph). Left side could be a little bit more narrow as well :-)

![image](https://user-images.githubusercontent.com/66269310/197834160-56f1cae3-c7ec-4fb6-9e9f-eaaf13ee5750.png)

Thx for your great work, 

Sebastian

**Comment by dbuezas** [comment]
This is a bit trickier because the right margin is reserved for a right axis, and the way I architected things, it is not known if a right axis will be used by the time the margins are computed.

**Comment by dbuezas** [comment]
On a side note, the humidity sensor in Martina's room seems to be very unstable. Consider the new statistics support (mean every 5 minutes or 1 hour) or using lambdas to smooth it out :)

**Comment by r-jean-pierre** [comment]
THe version 1.4.7 fixed the title margins,
before:
![2022-10-29 10_21_22-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198821863-0bad6ff1-599e-478d-83a3-9624b194b708.png)
after:
![2022-10-29 10_22_07-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198821869-cfa9d142-b2e6-4ead-9b86-9fdf54184e39.png)
Great job!

**Comment by dbuezas** [comment]
🎉 awesome!
BTW, your top margin looks a bit too big. You probably have some extra `margin: {t: 70}` or something like that. You can remove it now :)

**Comment by r-jean-pierre** [comment]
> 

Yeah, I did it but after the screenshot, I even realign better the rangeselector. An extra question to you: I expected to change the title size by using something like 
```yaml
layout:
  title:
    font:
      size: something there
```
but I failed, any idea?

**Comment by dbuezas** [comment]
Yes, that's because the title isn't the plotly title but a dedicated html element. I tried really hard, but when showing the legend at the top, either the legend would overlap with the plot, or the title with the legend. Quite frustrating.

You can check out these branches to see the only visually reasonable alternatives I found:
- [overlap-fix/dedicated-html-title-element](https://github.com/dbuezas/lovelace-plotly-graph-card/tree/overlap-fix/dedicated-html-title-element)
- [overlap-fix/legend-at-the-bottom](https://github.com/dbuezas/lovelace-plotly-graph-card/tree/overlap-fix/legend-at-the-bottom)
- [overlap-fix/legend-inside-plot](https://github.com/dbuezas/lovelace-plotly-graph-card/tree/overlap-fix/legend-inside-plot)

I could pass the font to the html element I guess...
At the moment if you want full customisation, you need to pass the title in the layout:
```yaml
layout:
  title:
    text: my title
    font:
      size: something there
```

If you find a better way, do let me know! (PR is ofc even better).

**Comment by dbuezas** [comment]
That looks great!
Have you considered this too? 
https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/13

**Comment by r-jean-pierre** [comment]
> 
Thanks!

So, if you mean one card displaying many entities at the same time, then yes and no. I may use the same card in different tabs for example dedicated to one unique room, or with a specific purpose such as heating monitoring. I never really know which strategy is the best, in general, I prefer duplicate cards than packing too much information in one unique place.

**Comment by dbuezas** [comment]
I'm a bit torn, but decided I'll close this issue in favour of https://github.com/dbuezas/lovelace-plotly-graph-card/pull/178. The extra right margin makes the upcoming show_value implementation look good. Otherwise it looks too clipped.

To reduce the right margin, it will have to be done manually via
```yaml
layout:
  margin:
    r: 30
```

Thanks anyway for the request. I even had it implemented (reduce right margin when only one yaxis is used), but IMO the new show_value is too useful, and adding extra logic to dynamically set he margin leads to too much custom tweaking for my taste. On the bright side, yaml configurability is what this card shines at :)
